# Generated by Django 5.1.3 on 2024-11-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programminglanguage',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='programminglanguage',
            index=models.Index(fields=['-time_create'], name='main_progra_time_cr_fa6e77_idx'),
        ),
    ]
