# Generated by Django 5.1.3 on 2024-11-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_programminglanguage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programminglanguage',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
