# Generated by Django 5.1.3 on 2024-11-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_programminglanguage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programminglanguage',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
