# Generated by Django 5.1.3 on 2024-11-30 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_programminglanguage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programminglanguage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.category'),
        ),
    ]
